version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  # Your app - BUILD from Dockerfile instead of using image
  app:
    image: yourusername/network-security-app:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/phishing_data
    depends_on:
      - mongodb

volumes:
  mongodb_data: